package com.sndi.model;
// Generated 23 juil. 2019 09:13:01 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Demande generated by hbm2java
 */
@Entity
@Table(name = "DEMANDE")
public class Demande implements java.io.Serializable {

	private String demCode;
	private TypeDemande typeDemande;
	private Usager usager;
	private String demNom;
	private String demPrenoms;
	private Date demDateNais;
	private String demLieuNais;
	private String demMobile;
	private String demEmail;
	private String demTel1;
	private String demTel2;
	private String demTypeExam;
	private String demCentreExam;
	private String demLocalite;
	private Date demAnneeObten;
	private String demSession;
	private String demNumTable;
	private BigDecimal demExempl;
	private String demModeRetrait;
	private String demModePaiement;
	private String demTypeOrganisme;
	private String demNomBen;
	private String demPrenomBen;
	private Date demDateNaisBen;
	private String demLieuNaisBen;
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<StatutDemande> statutDemandes = new HashSet<StatutDemande>(0);

	public Demande() {
	}

	public Demande(String demCode) {
		this.demCode = demCode;
	}

	public Demande(String demCode, TypeDemande typeDemande, Usager usager, String demNom, String demPrenoms,
			Date demDateNais, String demLieuNais, String demMobile, String demEmail, String demTel1, String demTel2,
			String demTypeExam, String demCentreExam, String demLocalite, Date demAnneeObten, String demSession,
			String demNumTable, BigDecimal demExempl, String demModeRetrait, String demModePaiement,
			String demTypeOrganisme, String demNomBen, String demPrenomBen, Date demDateNaisBen, String demLieuNaisBen,
			Set<Document> documents, Set<StatutDemande> statutDemandes) {
		this.demCode = demCode;
		this.typeDemande = typeDemande;
		this.usager = usager;
		this.demNom = demNom;
		this.demPrenoms = demPrenoms;
		this.demDateNais = demDateNais;
		this.demLieuNais = demLieuNais;
		this.demMobile = demMobile;
		this.demEmail = demEmail;
		this.demTel1 = demTel1;
		this.demTel2 = demTel2;
		this.demTypeExam = demTypeExam;
		this.demCentreExam = demCentreExam;
		this.demLocalite = demLocalite;
		this.demAnneeObten = demAnneeObten;
		this.demSession = demSession;
		this.demNumTable = demNumTable;
		this.demExempl = demExempl;
		this.demModeRetrait = demModeRetrait;
		this.demModePaiement = demModePaiement;
		this.demTypeOrganisme = demTypeOrganisme;
		this.demNomBen = demNomBen;
		this.demPrenomBen = demPrenomBen;
		this.demDateNaisBen = demDateNaisBen;
		this.demLieuNaisBen = demLieuNaisBen;
		this.documents = documents;
		this.statutDemandes = statutDemandes;
	}

	@Id

	@Column(name = "DEM_CODE", unique = true, nullable = false, length = 20)
	public String getDemCode() {
		return this.demCode;
	}

	public void setDemCode(String demCode) {
		this.demCode = demCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYD_CODE")
	public TypeDemande getTypeDemande() {
		return this.typeDemande;
	}

	public void setTypeDemande(TypeDemande typeDemande) {
		this.typeDemande = typeDemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USA_CODE")
	public Usager getUsager() {
		return this.usager;
	}

	public void setUsager(Usager usager) {
		this.usager = usager;
	}

	@Column(name = "DEM_NOM", length = 50)
	public String getDemNom() {
		return this.demNom;
	}

	public void setDemNom(String demNom) {
		this.demNom = demNom;
	}

	@Column(name = "DEM_PRENOMS", length = 250)
	public String getDemPrenoms() {
		return this.demPrenoms;
	}

	public void setDemPrenoms(String demPrenoms) {
		this.demPrenoms = demPrenoms;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEM_DATE_NAIS", length = 7)
	public Date getDemDateNais() {
		return this.demDateNais;
	}

	public void setDemDateNais(Date demDateNais) {
		this.demDateNais = demDateNais;
	}

	@Column(name = "DEM_LIEU_NAIS", length = 250)
	public String getDemLieuNais() {
		return this.demLieuNais;
	}

	public void setDemLieuNais(String demLieuNais) {
		this.demLieuNais = demLieuNais;
	}

	@Column(name = "DEM_MOBILE", length = 20)
	public String getDemMobile() {
		return this.demMobile;
	}

	public void setDemMobile(String demMobile) {
		this.demMobile = demMobile;
	}

	@Column(name = "DEM_EMAIL", length = 250)
	public String getDemEmail() {
		return this.demEmail;
	}

	public void setDemEmail(String demEmail) {
		this.demEmail = demEmail;
	}

	@Column(name = "DEM_TEL1", length = 20)
	public String getDemTel1() {
		return this.demTel1;
	}

	public void setDemTel1(String demTel1) {
		this.demTel1 = demTel1;
	}

	@Column(name = "DEM_TEL2", length = 20)
	public String getDemTel2() {
		return this.demTel2;
	}

	public void setDemTel2(String demTel2) {
		this.demTel2 = demTel2;
	}

	@Column(name = "DEM_TYPE_EXAM", length = 250)
	public String getDemTypeExam() {
		return this.demTypeExam;
	}

	public void setDemTypeExam(String demTypeExam) {
		this.demTypeExam = demTypeExam;
	}

	@Column(name = "DEM_CENTRE_EXAM", length = 250)
	public String getDemCentreExam() {
		return this.demCentreExam;
	}

	public void setDemCentreExam(String demCentreExam) {
		this.demCentreExam = demCentreExam;
	}

	@Column(name = "DEM_LOCALITE", length = 250)
	public String getDemLocalite() {
		return this.demLocalite;
	}

	public void setDemLocalite(String demLocalite) {
		this.demLocalite = demLocalite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEM_ANNEE_OBTEN", length = 7)
	public Date getDemAnneeObten() {
		return this.demAnneeObten;
	}

	public void setDemAnneeObten(Date demAnneeObten) {
		this.demAnneeObten = demAnneeObten;
	}

	@Column(name = "DEM_SESSION", length = 20)
	public String getDemSession() {
		return this.demSession;
	}

	public void setDemSession(String demSession) {
		this.demSession = demSession;
	}

	@Column(name = "DEM_NUM_TABLE", length = 20)
	public String getDemNumTable() {
		return this.demNumTable;
	}

	public void setDemNumTable(String demNumTable) {
		this.demNumTable = demNumTable;
	}

	@Column(name = "DEM_EXEMPL", precision = 22, scale = 0)
	public BigDecimal getDemExempl() {
		return this.demExempl;
	}

	public void setDemExempl(BigDecimal demExempl) {
		this.demExempl = demExempl;
	}

	@Column(name = "DEM_MODE_RETRAIT", length = 50)
	public String getDemModeRetrait() {
		return this.demModeRetrait;
	}

	public void setDemModeRetrait(String demModeRetrait) {
		this.demModeRetrait = demModeRetrait;
	}

	@Column(name = "DEM_MODE_PAIEMENT", length = 50)
	public String getDemModePaiement() {
		return this.demModePaiement;
	}

	public void setDemModePaiement(String demModePaiement) {
		this.demModePaiement = demModePaiement;
	}

	@Column(name = "DEM_TYPE_ORGANISME", length = 100)
	public String getDemTypeOrganisme() {
		return this.demTypeOrganisme;
	}

	public void setDemTypeOrganisme(String demTypeOrganisme) {
		this.demTypeOrganisme = demTypeOrganisme;
	}

	@Column(name = "DEM_NOM_BEN", length = 100)
	public String getDemNomBen() {
		return this.demNomBen;
	}

	public void setDemNomBen(String demNomBen) {
		this.demNomBen = demNomBen;
	}

	@Column(name = "DEM_PRENOM_BEN", length = 250)
	public String getDemPrenomBen() {
		return this.demPrenomBen;
	}

	public void setDemPrenomBen(String demPrenomBen) {
		this.demPrenomBen = demPrenomBen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEM_DATE_NAIS_BEN", length = 7)
	public Date getDemDateNaisBen() {
		return this.demDateNaisBen;
	}

	public void setDemDateNaisBen(Date demDateNaisBen) {
		this.demDateNaisBen = demDateNaisBen;
	}

	@Column(name = "DEM_LIEU_NAIS_BEN", length = 250)
	public String getDemLieuNaisBen() {
		return this.demLieuNaisBen;
	}

	public void setDemLieuNaisBen(String demLieuNaisBen) {
		this.demLieuNaisBen = demLieuNaisBen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<StatutDemande> getStatutDemandes() {
		return this.statutDemandes;
	}

	public void setStatutDemandes(Set<StatutDemande> statutDemandes) {
		this.statutDemandes = statutDemandes;
	}

}
