package com.sndi.model;
// Generated 23 juil. 2019 09:13:01 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT")
public class Document implements java.io.Serializable {

	private long docId;
	private Demande demande;
	private String docNature;
	private String docSource;
	private Serializable docDate;
	private String docSize;
	private String docEtat;

	public Document() {
	}

	public Document(long docId) {
		this.docId = docId;
	}

	public Document(long docId, Demande demande, String docNature, String docSource, Serializable docDate,
			String docSize, String docEtat) {
		this.docId = docId;
		this.demande = demande;
		this.docNature = docNature;
		this.docSource = docSource;
		this.docDate = docDate;
		this.docSize = docSize;
		this.docEtat = docEtat;
	}

	@Id
	@SequenceGenerator(name = "SEQ_DOC_Sequence", sequenceName = "SEQ_DOC", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_DOC_Sequence")
	@Column(name = "DOC_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDocId() {
		return this.docId;
	}

	public void setDocId(long docId) {
		this.docId = docId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEM_CODE")
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@Column(name = "DOC_NATURE", length = 200)
	public String getDocNature() {
		return this.docNature;
	}

	public void setDocNature(String docNature) {
		this.docNature = docNature;
	}

	@Column(name = "DOC_SOURCE")
	public String getDocSource() {
		return this.docSource;
	}

	public void setDocSource(String docSource) {
		this.docSource = docSource;
	}

	@Column(name = "DOC_DATE")
	public Serializable getDocDate() {
		return this.docDate;
	}

	public void setDocDate(Serializable docDate) {
		this.docDate = docDate;
	}

	@Column(name = "DOC_SIZE", length = 100)
	public String getDocSize() {
		return this.docSize;
	}

	public void setDocSize(String docSize) {
		this.docSize = docSize;
	}

	@Column(name = "DOC_ETAT", length = 100)
	public String getDocEtat() {
		return this.docEtat;
	}

	public void setDocEtat(String docEtat) {
		this.docEtat = docEtat;
	}

}
