package com.sndi.model;
// Generated 23 juil. 2019 09:13:01 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statut generated by hbm2java
 */
@Entity
@Table(name = "STATUT")
public class Statut implements java.io.Serializable {

	private String statutCode;
	private String statutLibelle;
	private Set<StatutDemande> statutDemandes = new HashSet<StatutDemande>(0);

	public Statut() {
	}

	public Statut(String statutCode) {
		this.statutCode = statutCode;
	}

	public Statut(String statutCode, String statutLibelle, Set<StatutDemande> statutDemandes) {
		this.statutCode = statutCode;
		this.statutLibelle = statutLibelle;
		this.statutDemandes = statutDemandes;
	}

	@Id

	@Column(name = "STATUT_CODE", unique = true, nullable = false, length = 10)
	public String getStatutCode() {
		return this.statutCode;
	}

	public void setStatutCode(String statutCode) {
		this.statutCode = statutCode;
	}

	@Column(name = "STATUT_LIBELLE", length = 254)
	public String getStatutLibelle() {
		return this.statutLibelle;
	}

	public void setStatutLibelle(String statutLibelle) {
		this.statutLibelle = statutLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statut")
	public Set<StatutDemande> getStatutDemandes() {
		return this.statutDemandes;
	}

	public void setStatutDemandes(Set<StatutDemande> statutDemandes) {
		this.statutDemandes = statutDemandes;
	}

}
