package com.sndi.model;
// Generated 7 sept. 2017 08:46:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysJournal generated by hbm2java
 */
@Entity
@Table(name = "SYS_JOURNAL")
public class SysJournal implements java.io.Serializable {

	private BigDecimal syjId;
	private Long assNum;
	private Date syjDateaction;
	private String syjIpAdresse;
	private String syjDescription;
	private String syjOpeMatricule;
	private String syjFonCod;

	public SysJournal() {
	}

	public SysJournal(BigDecimal syjId) {
		this.syjId = syjId;
	}

	public SysJournal(BigDecimal syjId, Long assNum, Date syjDateaction, String syjIpAdresse, String syjDescription
			, String syjOpeMatricule, String syjFonCod) {
		this.syjId = syjId;
		this.assNum = assNum;
		this.syjDateaction = syjDateaction;
		this.syjIpAdresse = syjIpAdresse;
		this.syjDescription = syjDescription;
		this.syjOpeMatricule = syjOpeMatricule;
		this.syjFonCod = syjFonCod;
	}

	@Id
	@SequenceGenerator(name = "SYJ_Sequence", sequenceName = "SEQ_SYJ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SYJ_Sequence")
	@Column(name = "SYJ_ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getSyjId() {
		return this.syjId;
	}

	public void setSyjId(BigDecimal syjId) {
		this.syjId = syjId;
	}


	@Column(name = "ASS_NUM", precision = 10, scale = 0)
	public Long getAssNum() {
		return this.assNum;
	}

	public void setAssNum(Long assNum) {
		this.assNum = assNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SYJ_DATEACTION", length = 7)
	public Date getSyjDateaction() {
		return this.syjDateaction;
	}

	public void setSyjDateaction(Date syjDateaction) {
		this.syjDateaction = syjDateaction;
	}
	
	@Column(name = "SYJ_IP_ADRESSE", length = 100)
	public String getSyjIpAdresse() {
		return syjIpAdresse;
	}

	public void setSyjIpAdresse(String syjIpAdresse) {
		this.syjIpAdresse = syjIpAdresse;
	}

	@Column(name = "SYJ_DESCRIPTION", length = 250)
	public String getSyjDescription() {
		return this.syjDescription;
	}

	public void setSyjDescription(String syjDescription) {
		this.syjDescription = syjDescription;
	}
	@Column(name = "SYJ_OPE_MATRICULE", length = 25)
	public String getSyjOpeMatricule() {
		return syjOpeMatricule;
	}

	public void setSyjOpeMatricule(String syjOpeMatricule) {
		this.syjOpeMatricule = syjOpeMatricule;
	}

	@Column(name = "SYJ_FON_COD", length = 12)
	public String getSyjFonCod() {
		return syjFonCod;
	}

	public void setSyjFonCod(String syjFonCod) {
		this.syjFonCod = syjFonCod;
	}
	
	

}
