package com.sndi.model;
// Generated 23 juil. 2019 09:13:01 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TFonction generated by hbm2java
 */
@Entity
@Table(name = "T_FONCTION")
public class TFonction implements java.io.Serializable {

	private String fonCod;
	private Structure structure;
	private TTypeFonction TTypeFonction;
	private Date fonDatDeb;
	private Date fonDatFin;
	private String fonLibelle;
	private Set<TAssignation> TAssignations = new HashSet<TAssignation>(0);
	private Set<StatutDemande> statutDemandes = new HashSet<StatutDemande>(0);
	private Set<SysJournal> sysJournals = new HashSet<SysJournal>(0);

	public TFonction() {
	}

	public TFonction(String fonCod) {
		this.fonCod = fonCod;
	}

	public TFonction(String fonCod, Structure structure, TTypeFonction TTypeFonction, Date fonDatDeb, Date fonDatFin,
			String fonLibelle, Set<TAssignation> TAssignations, Set<StatutDemande> statutDemandes,
			Set<SysJournal> sysJournals) {
		this.fonCod = fonCod;
		this.structure = structure;
		this.TTypeFonction = TTypeFonction;
		this.fonDatDeb = fonDatDeb;
		this.fonDatFin = fonDatFin;
		this.fonLibelle = fonLibelle;
		this.TAssignations = TAssignations;
		this.statutDemandes = statutDemandes;
		this.sysJournals = sysJournals;
	}

	@Id

	@Column(name = "FON_COD", unique = true, nullable = false, length = 12)
	public String getFonCod() {
		return this.fonCod;
	}

	public void setFonCod(String fonCod) {
		this.fonCod = fonCod;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STR_CODE")
	public Structure getStructure() {
		return this.structure;
	}

	public void setStructure(Structure structure) {
		this.structure = structure;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TYF_COD")
	public TTypeFonction getTTypeFonction() {
		return this.TTypeFonction;
	}

	public void setTTypeFonction(TTypeFonction TTypeFonction) {
		this.TTypeFonction = TTypeFonction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FON_DAT_DEB", length = 7)
	public Date getFonDatDeb() {
		return this.fonDatDeb;
	}

	public void setFonDatDeb(Date fonDatDeb) {
		this.fonDatDeb = fonDatDeb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FON_DAT_FIN", length = 7)
	public Date getFonDatFin() {
		return this.fonDatFin;
	}

	public void setFonDatFin(Date fonDatFin) {
		this.fonDatFin = fonDatFin;
	}

	@Column(name = "FON_LIBELLE", length = 240)
	public String getFonLibelle() {
		return this.fonLibelle;
	}

	public void setFonLibelle(String fonLibelle) {
		this.fonLibelle = fonLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFonction")
	public Set<TAssignation> getTAssignations() {
		return this.TAssignations;
	}

	public void setTAssignations(Set<TAssignation> TAssignations) {
		this.TAssignations = TAssignations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFonction")
	public Set<StatutDemande> getStatutDemandes() {
		return this.statutDemandes;
	}

	public void setStatutDemandes(Set<StatutDemande> statutDemandes) {
		this.statutDemandes = statutDemandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFonction")
	public Set<SysJournal> getSysJournals() {
		return this.sysJournals;
	}

	public void setSysJournals(Set<SysJournal> sysJournals) {
		this.sysJournals = sysJournals;
	}

}
