package com.sndi.model;
// Generated 7 sept. 2017 08:46:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TMotdepasse generated by hbm2java
 */
@Entity
@Table(name = "T_MOTDEPASSE")
public class TMotdepasse implements java.io.Serializable {

	private long mdpId;
	private TOperateur TOperateur;
	private String mdpMotdepasse;
	private Boolean mdpStatut;
	private Date mdpDate;
	private String mdpMotdepasseInit;

	public TMotdepasse() {
	}

	public TMotdepasse(long mdpId) {
		this.mdpId = mdpId;
	}

	public TMotdepasse(long mdpId, TOperateur TOperateur, String mdpMotdepasse, Boolean mdpStatut, Date mdpDate) {
		this.mdpId = mdpId;
		this.TOperateur = TOperateur;
		this.mdpMotdepasse = mdpMotdepasse;
		this.mdpStatut = mdpStatut;
		this.mdpDate = mdpDate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_MDP_Sequence", sequenceName = "SEQ_MDP", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_MDP_Sequence")
	@Column(name = "MDP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMdpId() {
		return this.mdpId;
	}

	public void setMdpId(long mdpId) {
		this.mdpId = mdpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPE_MATRICULE")
	public TOperateur getTOperateur() {
		return this.TOperateur;
	}

	public void setTOperateur(TOperateur TOperateur) {
		this.TOperateur = TOperateur;
	}

	@Column(name = "MDP_MOTDEPASSE", length = 250)
	public String getMdpMotdepasse() {
		return this.mdpMotdepasse;
	}

	public void setMdpMotdepasse(String mdpMotdepasse) {
		this.mdpMotdepasse = mdpMotdepasse;
	}

	@Column(name = "MDP_STATUT", precision = 1, scale = 0)
	public Boolean getMdpStatut() {
		return this.mdpStatut;
	}

	public void setMdpStatut(Boolean mdpStatut) {
		this.mdpStatut = mdpStatut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MDP_DATE", length = 7)
	public Date getMdpDate() {
		return this.mdpDate;
	}

	public void setMdpDate(Date mdpDate) {
		this.mdpDate = mdpDate;
	}

	@Column(name = "MDP_MOTDEPASSE_INIT", length = 250)
	public String getMdpMotdepasseInit() {
		return mdpMotdepasseInit;
	}

	public void setMdpMotdepasseInit(String mdpMotdepasseInit) {
		this.mdpMotdepasseInit = mdpMotdepasseInit;
	}

}
