package com.sndi.model;
// Generated 7 sept. 2017 08:46:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TOperateur generated by hbm2java
 */
@Entity
@Table(name = "T_OPERATEUR")
public class TOperateur implements java.io.Serializable {

	private String opeMatricule;
	private String opeNom;
	private String opeContact;
	private String opeEtatCivil;
	private String opeMail;
	private String opeLogin;
	private Date opeDconnexion;
	private Set<TAssignation> TAssignations = new HashSet<TAssignation>(0);
	private Set<TMotdepasse> TMotdepasses = new HashSet<TMotdepasse>(0);

	public TOperateur() {
	}

	public TOperateur(String opeMatricule) {
		this.opeMatricule = opeMatricule;
	}

	public TOperateur(String opeMatricule, String opeNom, String opeContact, String opeEtatCivil, String opeMail,
			String opeLogin, Date opeDconnexion, Set<TAssignation> TAssignations, Set<TMotdepasse> TMotdepasses) {
		this.opeMatricule = opeMatricule;
		this.opeNom = opeNom;
		this.opeContact = opeContact;
		this.opeEtatCivil = opeEtatCivil;
		this.opeMail = opeMail;
		this.opeLogin = opeLogin;
		this.opeDconnexion = opeDconnexion;
		this.TAssignations = TAssignations;
		this.TMotdepasses = TMotdepasses;
	}

	@Id

	@Column(name = "OPE_MATRICULE", unique = true, nullable = false, length = 25)
	public String getOpeMatricule() {
		return this.opeMatricule;
	}

	public void setOpeMatricule(String opeMatricule) {
		this.opeMatricule = opeMatricule;
	}

	@Column(name = "OPE_NOM")
	public String getOpeNom() {
		return this.opeNom;
	}

	public void setOpeNom(String opeNom) {
		this.opeNom = opeNom;
	}

	@Column(name = "OPE_CONTACT", length = 250)
	public String getOpeContact() {
		return this.opeContact;
	}

	public void setOpeContact(String opeContact) {
		this.opeContact = opeContact;
	}

	@Column(name = "OPE_ETAT_CIVIL", length = 250)
	public String getOpeEtatCivil() {
		return this.opeEtatCivil;
	}

	public void setOpeEtatCivil(String opeEtatCivil) {
		this.opeEtatCivil = opeEtatCivil;
	}

	@Column(name = "OPE_MAIL", length = 250)
	public String getOpeMail() {
		return this.opeMail;
	}

	public void setOpeMail(String opeMail) {
		this.opeMail = opeMail;
	}

	@Column(name = "OPE_LOGIN", length = 50)
	public String getOpeLogin() {
		return this.opeLogin;
	}

	public void setOpeLogin(String opeLogin) {
		this.opeLogin = opeLogin;
	}
		

	@Temporal(TemporalType.DATE)
	@Column(name = "OPE_DCONNEXION", length = 13)
	public Date getOpeDconnexion() {
		return opeDconnexion;
	}

	public void setOpeDconnexion(Date opeDconnexion) {
		this.opeDconnexion = opeDconnexion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOperateur")
	@Fetch(FetchMode.SELECT)
	public Set<TAssignation> getTAssignations() {
		return this.TAssignations;
	}

	public void setTAssignations(Set<TAssignation> TAssignations) {
		this.TAssignations = TAssignations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOperateur")
	@Fetch(FetchMode.SELECT)
	public Set<TMotdepasse> getTMotdepasses() {
		return this.TMotdepasses;
	}

	public void setTMotdepasses(Set<TMotdepasse> TMotdepasses) {
		this.TMotdepasses = TMotdepasses;
	}

}
