package com.sndi.model;
// Generated 23 juil. 2019 09:13:01 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Usager generated by hbm2java
 */
@Entity
@Table(name = "USAGER")
public class Usager implements java.io.Serializable {

	private long usaCode;
	private String usaNom;
	private String usaPrenoms;
	private String usaLogin;
	private String usaMdp;
	private String usaEmail;
	private String usaMobile;
	private String usaContact;
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Usager() {
	}

	public Usager(long usaCode) {
		this.usaCode = usaCode;
	}

	public Usager(long usaCode, String usaNom, String usaPrenoms, String usaLogin, String usaMdp, String usaEmail,
			String usaMobile, String usaContact, Set<Demande> demandes) {
		this.usaCode = usaCode;
		this.usaNom = usaNom;
		this.usaPrenoms = usaPrenoms;
		this.usaLogin = usaLogin;
		this.usaMdp = usaMdp;
		this.usaEmail = usaEmail;
		this.usaMobile = usaMobile;
		this.usaContact = usaContact;
		this.demandes = demandes;
	}

	@Id
	@SequenceGenerator(name = "SEQ_USA_Sequence", sequenceName = "SEQ_USA", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_USA_Sequence")
	@Column(name = "USA_CODE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getUsaCode() {
		return this.usaCode;
	}

	public void setUsaCode(long usaCode) {
		this.usaCode = usaCode;
	}

	@Column(name = "USA_NOM", length = 100)
	public String getUsaNom() {
		return this.usaNom;
	}

	public void setUsaNom(String usaNom) {
		this.usaNom = usaNom;
	}

	@Column(name = "USA_PRENOMS", length = 250)
	public String getUsaPrenoms() {
		return this.usaPrenoms;
	}

	public void setUsaPrenoms(String usaPrenoms) {
		this.usaPrenoms = usaPrenoms;
	}

	@Column(name = "USA_LOGIN", length = 100)
	public String getUsaLogin() {
		return this.usaLogin;
	}

	public void setUsaLogin(String usaLogin) {
		this.usaLogin = usaLogin;
	}

	@Column(name = "USA_MDP", length = 250)
	public String getUsaMdp() {
		return this.usaMdp;
	}

	public void setUsaMdp(String usaMdp) {
		this.usaMdp = usaMdp;
	}

	@Column(name = "USA_EMAIL", length = 250)
	public String getUsaEmail() {
		return this.usaEmail;
	}

	public void setUsaEmail(String usaEmail) {
		this.usaEmail = usaEmail;
	}

	@Column(name = "USA_MOBILE", length = 20)
	public String getUsaMobile() {
		return this.usaMobile;
	}

	public void setUsaMobile(String usaMobile) {
		this.usaMobile = usaMobile;
	}

	@Column(name = "USA_CONTACT", length = 500)
	public String getUsaContact() {
		return this.usaContact;
	}

	public void setUsaContact(String usaContact) {
		this.usaContact = usaContact;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usager")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
